name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y

      - name: Build for debian
        run: xvfb-run ./scripts/build.sh

      - name: Upload to release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          file: ./build/webview
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build for MacOS
        run: ./scripts/build.sh

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build for windows
        run: ./scripts/build.bat

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./build/webview.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}